// This file is generated by a script. Do not modify this file manually.

/* eslint-disable prettier/prettier */

interface BadgeExtraProps {
  variation?: "default" | "default_outline" | "primary" | "primary_outline" | "secondary" | "secondary_outline" | "tertiary" | "tertiary_outline";
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
}

interface ButtonExtraProps {
  variation?: "default" | "primary" | "primary_outline" | "secondary" | "secondary_outline" | "tertiary" | "tertiary_outline" | "danger" | "success";
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
  pressed?: boolean;
  disabled?: boolean;
  loading?: boolean;
}

interface CheckboxExtraProps {
  variation?: "default" | "primary" | "secondary" | "tertiary";
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
  disabled?: boolean;
}

interface LabelExtraProps {
  variation?: "default" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "p" | "quot" | "small";
  bold?: boolean;
  italic?: boolean;
  weight?: "light" | "regular" | "medium" | "semiBold" | "bold";
}

interface RadioExtraProps {
  variation?: "default" | "primary" | "secondary" | "tertiary";
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
  disabled?: boolean;
}

interface RadioGroupExtraProps {
  variation?: "default";
  disabled?: boolean;
}

interface PopupExtraProps {
}

interface TabExtraProps {
}

interface StepperExtraProps {
}

interface ImageExtraProps {
}

interface BlockExtraProps {
}

interface ColExtraProps {
}

interface RowExtraProps {
}

interface LabelExtraProps {
}

interface ListExtraProps {
}

interface LinkExtraProps {

}

interface SelectExtraProps {

}

interface SliderExtraProps {

}

interface SwitchExtraProps {

}

interface TextfieldExtraProps {
  
}