// This file is generated by a script. Do not modify this file manually.

/* eslint-disable prettier/prettier */

interface AccordionExtraProps {
  variation?: "default";
  disabled?: boolean;
}

interface AvatarExtraProps {
  variation?: "default" | "rounded" | "square";
  size?: "xs" | "sm" | "md" | "lg" | "xl";
}

interface BadgeExtraProps {
  variation?: "default" | "default_outline" | "primary" | "primary_outline" | "secondary" | "secondary_outline" | "tertiary" | "tertiary_outline";
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
}

interface BlockExtraProps {
  variation?: "default";
}

interface ButtonExtraProps {
  variation?: "default" | "primary" | "primary_outline" | "secondary" | "secondary_outline" | "tertiary" | "tertiary_outline" | "danger" | "success";
  full?: boolean;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
  pressed?: boolean;
  disabled?: boolean;
  loading?: boolean;
}

interface CheckboxExtraProps {
  variation?: "default" | "primary" | "secondary" | "tertiary";
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
  pressed?: boolean;
  disabled?: boolean;
}

interface ColExtraProps {
  variation?: "default";
}

interface DatepickerExtraProps {
  variation?: "default";
  focus?: boolean;
  error?: boolean;
  disabled?: boolean;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
  textarea?: boolean;
}

interface ImageExtraProps {
  variation?: "default";
  background?: boolean;
}

interface LabelExtraProps {
  variation?: "default" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "p" | "quot" | "small";
  bold?: boolean;
  italic?: boolean;
  weight?: "light" | "regular" | "medium" | "semiBold" | "bold";
}

interface LinkExtraProps {
  variation?: "default" | "primary" | "secondary" | "tertiary";
}

interface ListExtraProps {
  variation?: "default";
}

interface PopupExtraProps {
  variation?: "default" | "info" | "success" | "warning" | "error";
}

interface RadioExtraProps {
  variation?: "default" | "primary" | "secondary" | "tertiary";
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
  disabled?: boolean;
}

interface RadioGroupExtraProps {
  variation?: "default";
  disabled?: boolean;
}

interface RowExtraProps {
  variation?: "default";
}

interface SelectExtraProps {
  variation?: "default";
  focus?: boolean;
  error?: boolean;
  disabled?: boolean;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
}

interface SliderExtraProps {
  variation?: "default";
  focus?: boolean;
  error?: boolean;
  disabled?: boolean;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
}

interface StepperExtraProps {
  variation?: "default";
  isActive?: boolean;
  isCompleted?: boolean;
  isDisabled?: boolean;
  isFirst?: boolean;
  isLast?: boolean;
}

interface SwitchExtraProps {
  variation?: "default" | "primary" | "secondary" | "tertiary";
  disabled?: boolean;
}

interface TabViewExtraProps {
  variation?: "default";
  active?: boolean;
}

interface TextfieldExtraProps {
  variation?: "default";
  focus?: boolean;
  disabled?: boolean;
  error?: boolean;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
  textarea?: boolean;
}

