// This file is generated by a script. Do not modify this file manually.

/* eslint-disable prettier/prettier */

interface TextfieldExtraProps {
  focus?: boolean;
  error?: boolean;
  disabled?: boolean;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
  textarea?: boolean;
}

interface SelectExtraProps {
  focus?: boolean;
  error?: boolean;
  disabled?: boolean;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
}

interface CheckboxExtraProps {
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
  focus?: boolean;
  error?: boolean;
  disabled?: boolean;
}

interface ButtonExtraProps {
  base?: "primary" | "secondary" | "tertiary";
  outline?: "primary" | "secondary" | "tertiary";
  disabled?: "primary" | "secondary" | "tertiary";
  half?: boolean;
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "xxl";
}

interface RadioExtraProps {
}

interface RadioGroupExtraProps {
}

interface SliderExtraProps {
  focus?: boolean;
  error?: boolean;
  disabled?: boolean;
  size?: "sm" | "md" | "lg";
}

interface SwitchExtraProps {
  focus?: boolean;
  error?: boolean;
  disabled?: boolean;
  size?: "sm" | "md" | "lg";
}

interface Accordion_headerExtraProps {
  disabled?: boolean;
}

interface Accordion_itemExtraProps {
  disabled?: boolean;
}

interface LinkExtraProps {
  primary?: boolean;
  secondary?: boolean;
}

interface BadgeExtraProps {
  base?: "primary" | "secondary" | "tertiary";
  outline?: "primary" | "secondary" | "tertiary" | "false" | boolean;
  primary?: boolean;
  secondary?: boolean;
  tertiary?: boolean;
}

interface PopupExtraProps {
}

interface TabExtraProps {
}

interface StepperExtraProps {
}

interface ImageExtraProps {
}

interface BlockExtraProps {
}

interface ColExtraProps {
}

interface RowExtraProps {
}

interface LabelExtraProps {
}

interface ListExtraProps {
}

