import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   "intro",
  //   {
  //     "Getting Started Guide": [
  //       "getting-started/manuel",
  //       "getting-started/with-cli",
  //     ],
  //   },
  //   {
  //     Components: [
  //       {
  //         type: "category",
  //         label: "Accordion",
  //         items: [
  //           "components/accordion/accordion-item",
  //           "components/accordion/accordion-list",
  //         ],
  //         link: { type: "doc", id: "components/accordion/accordion" },
  //       },
  //       "components/avatar",
  //       "components/badge",
  //       "components/block",
  //       "components/bottom-sheet",
  //       "components/button",
  //       "components/checkbox",
  //       "components/datepicker",
  //       "components/form",
  //       "components/image",
  //       "components/input-group",
  //       "components/label",
  //       "components/link",
  //       "components/list",
  //       "components/lucide-icon",
  //       "components/popup",
  //       "components/provider",
  //       "components/radio",
  //       "components/rowcol",
  //       "components/select",
  //       "components/slider",
  //       "components/slot",
  //     ],
  //   },
  // ],
};

export default sidebars;
